components:
  schemas:
    CreateAccountRequest:
      additionalProperties: false
      description: Request to create an account
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
      required:
      - email
      - password
      - username
      title: CreateAccountRequest
      type: object
    CreateAccountResponse:
      additionalProperties: false
      description: Response to account creation
      properties:
        message:
          type: string
        success:
          type: boolean
      title: CreateAccountResponse
      type: object
    Error:
      additionalProperties: false
      properties:
        errors:
          type: object
        message:
          type: string
      required:
      - message
      title: Error
      type: object
    LoginRequest:
      additionalProperties: false
      description: Request to login
      properties:
        password:
          type: string
        username:
          type: string
      required:
      - password
      - username
      title: LoginRequest
      type: object
    LoginResponse:
      additionalProperties: false
      description: Response to login
      properties:
        success:
          type: boolean
      title: LoginResponse
      type: object
    TestResponse:
      additionalProperties: false
      description: Test response
      properties:
        message:
          type: string
      title: TestResponse
      type: object
info:
  description: Hangboard hard!!!!
  title: Hangboard
  version: 1.0.0
openapi: 3.0.2
paths:
  /api/hello:
    get:
      description: Return the test response
      operationId: get_hello
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
          description: Test response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
  /api/join:
    post:
      operationId: create_account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
          description: Response to account creation
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
  /api/login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: Response to login
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error

