/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/hello": {
    /** @description Return the test response */
    get: operations["get_hello"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Error */
    Error: {
      errors?: Record<string, never>;
      message: string;
    };
    /**
     * TestResponse 
     * @description Test response
     */
    TestResponse: {
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description Return the test response */
  get_hello: {
    responses: {
      /** @description Test response */
      200: {
        content: {
          "application/json": components["schemas"]["TestResponse"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
